version: '3.8'
services:
    openmote:
        build: "./"
        volumes:
            - "./:/app"
        stdin_open: true
        tty: true
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
            - "/dev/ttyUSB1:/dev/ttyUSB1"
